openapi: 3.0.0
info:
  title: API fil rouge formation CDA
  description: Cette API permet de gérer les posts d'un blog.
  version: "1.0.0"
servers:
  - url: http://localhost:8080
paths:
  /:
   get:
    summary:
    responses:
      '200':
        description: Hello World
        content:
          text/plain:
            schema:
              type: string
              example: Hello World pas piqué des hannetons